### ISSUE TITLE
load_gridded_forecast leads to strange forecast plots

### ISSUE THREAD

**Issue by kirstybayliss** [SCECcode/pycsep#42] opened 2020-09-29 10:55 UTC
I had some interesting results using load_gridded_forecast, where the forecast loads and the region midpoint locations match with the examples, but when plotted it's clear that the intensity values are mapping to the wrong grid cells. I think this is related to forecast.region which maybe assumes or internally sorts longitudes of the grid cells in a certain order, hence the matching region midpoints. The plotting function takes the lon/lats from the region but the intensities are assigned based on the arrangement of the input file, which I think is what leads to this:

![Kirsty_forecast_plot](https://user-images.githubusercontent.com/37081055/94547637-70015080-0247-11eb-8615-69ace3a12c97.png)

Sorting my gridded forecast file so the longitudes are in ascending order before loading let me load a forecast that had the expected spatial pattern (more smoothed seismicity than the above!).

**Comment by wsavran** [comment] 2020-09-29 16:47
kirsty do you mind attaching the forecasting file you used here? id like to dig into this a bit more. at first glace, im not exactly sure what is causing this issue. even the plotting part appears to be correctly ordering the points.

**Comment by kirstybayliss** [comment] 2020-09-29 18:16
Sure, [CSEP_test1_wonky.txt](https://github.com/SCECcode/pycsep/files/5300948/CSEP_test1_wonky.txt) will generate the above for me with `forecast.plot()` and [CSEP_test1_lonSort.txt](https://github.com/SCECcode/pycsep/files/5300946/CSEP_test1_lonSort.txt) is identical except sorted by longitude which plots this:
![fixed_plot](https://user-images.githubusercontent.com/37081055/94598231-94305200-0286-11eb-9d43-a0cd4f294e31.png)

These forecasts also get different  `spatial_test` results, which I guess shouldn't be the case if it's purely a plotting issue?
(Github wouldn't let me upload these as .dat files, but that's how I've been loading them)

**Comment by wsavran** [comment] 2020-09-29 22:56
thanks for sharing. the `.dat` is just an ascii file, so that is not a problem. ill take a look at this and figure out whats going on with the sorting issues. let me know if you find out anything else.

**Comment by wsavran** [comment] 2020-10-03 22:33
the issue was in the `load_gridded_forecast` function, and was caused by the `numpy.unique` function used to pull out the unique lat / lon cells. this function by default returns a sorted list of unique values.

**Comment by wsavran** [comment] 2020-10-05 15:53
closed with #47. if you have installed pycsep from source, you can just pull the latest updates to get this fix. if you used conda-forge or pypi distribution these will be included in the next release.

**Closed by wsavran** 2020-10-05 15:53 UTC
